<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Map slug → category id
        $cats = Category::pluck('id', 'slug');

        $products = [
            [
                'brand'         => 'Optimum Nutrition',
                'name'          => 'بروتين واي الذهبي - شوكولاتة مزدوجة',
                'slug'          => 'whey-gold-double-chocolate-optimum-nutrition',
                'description'   => 'بروتين واي عالي الجودة بنكهة الشوكولاتة المزدوجة. 24 جرام بروتين في كل وجبة، مثالي لبناء العضلات والتعافي بعد التمرين.',
                'price'         => 189.00,
                'old_price'     => 260.00,
                'image_url'     => 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=300&q=80',
                'badge'         => 'sale',
                'discount'      => 27,
                'rating'        => 4.9,
                'reviews_count' => 1248,
                'stock'         => 45,
                'category_slug' => 'protein',
            ],
            [
                'brand'         => 'Garden of Life',
                'name'          => 'فيتامين D3 + K2 لصحة العظام',
                'slug'          => 'vitamin-d3-k2-garden-of-life',
                'description'   => 'مزيج متكامل من فيتامين D3 وK2 لتعزيز صحة العظام والمناعة. مستخرج من مصادر طبيعية 100%.',
                'price'         => 95.00,
                'old_price'     => 130.00,
                'image_url'     => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&q=80',
                'badge'         => 'best',
                'discount'      => 26,
                'rating'        => 4.8,
                'reviews_count' => 876,
                'stock'         => 60,
                'category_slug' => 'vitamins',
            ],
            [
                'brand'         => 'NOW Foods',
                'name'          => 'أوميغا 3 زيت السمك - 180 كبسولة',
                'slug'          => 'omega3-fish-oil-180-now-foods',
                'description'   => 'زيت سمك عالي التركيز غني بأحماض EPA وDHA الأساسية لدعم صحة القلب والدماغ.',
                'price'         => 78.00,
                'old_price'     => null,
                'image_url'     => 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=300&q=80',
                'badge'         => 'new',
                'discount'      => 0,
                'rating'        => 4.7,
                'reviews_count' => 654,
                'stock'         => 80,
                'category_slug' => 'omega',
            ],
            [
                'brand'         => 'Myprotein',
                'name'          => 'كرياتين مونوهيدرات 100% نقي 500غ',
                'slug'          => 'creatine-monohydrate-500g-myprotein',
                'description'   => 'كرياتين مونوهيدرات نقي 100% بدون إضافات. يعزز القوة والأداء الرياضي ويزيد كتلة العضلات.',
                'price'         => 55.00,
                'old_price'     => 75.00,
                'image_url'     => 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?w=300&q=80',
                'badge'         => 'hot',
                'discount'      => 27,
                'rating'        => 4.9,
                'reviews_count' => 2103,
                'stock'         => 120,
                'category_slug' => 'sport',
            ],
            [
                'brand'         => 'Solgar',
                'name'          => 'مغنيسيوم سيترات لجودة النوم',
                'slug'          => 'magnesium-citrate-solgar',
                'description'   => 'مغنيسيوم سيترات عالي الامتصاص لتحسين جودة النوم وتخفيف التوتر والقلق.',
                'price'         => 88.00,
                'old_price'     => 110.00,
                'image_url'     => 'https://images.unsplash.com/photo-1626285861696-9f0bf5a49c6d?w=300&q=80',
                'badge'         => 'sale',
                'discount'      => 20,
                'rating'        => 4.6,
                'reviews_count' => 432,
                'stock'         => 35,
                'category_slug' => 'vitamins',
            ],
            [
                'brand'         => "Nature's Way",
                'name'          => 'كولاجين مارين مع فيتامين C',
                'slug'          => 'marine-collagen-vitamin-c-natures-way',
                'description'   => 'كولاجين بحري من أسماك المياه الباردة مع فيتامين C لتعزيز نضارة البشرة وصحة المفاصل.',
                'price'         => 145.00,
                'old_price'     => 195.00,
                'image_url'     => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&q=80',
                'badge'         => 'best',
                'discount'      => 25,
                'rating'        => 4.8,
                'reviews_count' => 789,
                'stock'         => 50,
                'category_slug' => 'skin',
            ],
            [
                'brand'         => 'BSN',
                'name'          => 'أحماض BCAA بالنكهات - 60 وجبة',
                'slug'          => 'bcaa-flavored-60-servings-bsn',
                'description'   => 'أحماض أمينية متشعبة BCAA 2:1:1 بنكهات متنوعة. تحمي العضلات وتسرع التعافي بعد التمرين.',
                'price'         => 110.00,
                'old_price'     => 140.00,
                'image_url'     => 'https://images.unsplash.com/photo-1594737625785-a6cbdabd333c?w=300&q=80',
                'badge'         => 'sale',
                'discount'      => 21,
                'rating'        => 4.7,
                'reviews_count' => 563,
                'stock'         => 40,
                'category_slug' => 'sport',
            ],
            [
                'brand'         => 'Jarrow',
                'name'          => 'بروبيوتيك قوي 50 مليار بكتيريا',
                'slug'          => 'probiotic-50b-jarrow',
                'description'   => '50 مليار وحدة من البكتيريا النافعة في كبسولة واحدة. يدعم صحة الجهاز الهضمي والمناعة.',
                'price'         => 125.00,
                'old_price'     => 160.00,
                'image_url'     => 'https://images.unsplash.com/photo-1609501659561-c1a5d9d935a8?w=300&q=80',
                'badge'         => null,
                'discount'      => 22,
                'rating'        => 4.5,
                'reviews_count' => 328,
                'stock'         => 25,
                'category_slug' => 'vitamins',
            ],
            [
                'brand'         => 'Nutricost',
                'name'          => 'L-Glutamine غلوتامين نقي 500غ',
                'slug'          => 'l-glutamine-500g-nutricost',
                'description'   => 'غلوتامين نقي 100% لدعم التعافي السريع وحماية الجهاز الهضمي وتعزيز المناعة.',
                'price'         => 68.00,
                'old_price'     => 88.00,
                'image_url'     => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=300&q=80',
                'badge'         => 'new',
                'discount'      => 22,
                'rating'        => 4.8,
                'reviews_count' => 945,
                'stock'         => 70,
                'category_slug' => 'sport',
            ],
            [
                'brand'         => 'MusclePharm',
                'name'          => 'حرق دهون Shred Sport - 60 كبسولة',
                'slug'          => 'shred-sport-60-musclepharm',
                'description'   => 'مكمل حرق دهون متطور يجمع بين الكافيين الطبيعي ومستخلصات الشاي الأخضر لتعزيز الحرق.',
                'price'         => 135.00,
                'old_price'     => 175.00,
                'image_url'     => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=300&q=80',
                'badge'         => 'hot',
                'discount'      => 23,
                'rating'        => 4.6,
                'reviews_count' => 712,
                'stock'         => 30,
                'category_slug' => 'weight',
            ],
            [
                'brand'         => 'Garden of Life',
                'name'          => 'فيتامين C نباتي 1000mg مع زنك',
                'slug'          => 'vitamin-c-1000mg-zinc-garden-of-life',
                'description'   => 'فيتامين C نباتي مستخرج من الأسيرولا والكيوي مع الزنك. يعزز المناعة ويحارب أضرار الجذور الحرة.',
                'price'         => 115.00,
                'old_price'     => null,
                'image_url'     => 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=300&q=80',
                'badge'         => 'new',
                'discount'      => 0,
                'rating'        => 4.7,
                'reviews_count' => 124,
                'stock'         => 55,
                'category_slug' => 'vitamins',
            ],
            [
                'brand'         => 'Optimum Nutrition',
                'name'          => 'بروتين نباتي أورجانيك - فانيليا',
                'slug'          => 'organic-plant-protein-vanilla-optimum',
                'description'   => 'بروتين نباتي عضوي مستخرج من البازلاء والأرز البني بنكهة الفانيليا الطبيعية.',
                'price'         => 215.00,
                'old_price'     => 260.00,
                'image_url'     => 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=300&q=80',
                'badge'         => 'new',
                'discount'      => 17,
                'rating'        => 4.6,
                'reviews_count' => 87,
                'stock'         => 20,
                'category_slug' => 'protein',
            ],
            [
                'brand'         => 'Solgar',
                'name'          => 'أشواغاندا KSM-66 للإجهاد',
                'slug'          => 'ashwagandha-ksm66-solgar',
                'description'   => 'مستخلص أشواغاندا KSM-66 الأكثر فاعلية لتقليل الإجهاد والقلق وتحسين مستوى الطاقة.',
                'price'         => 99.00,
                'old_price'     => 135.00,
                'image_url'     => 'https://images.unsplash.com/photo-1612540139150-4b5bdd9e9d36?w=300&q=80',
                'badge'         => 'new',
                'discount'      => 26,
                'rating'        => 4.8,
                'reviews_count' => 203,
                'stock'         => 40,
                'category_slug' => 'herbs',
            ],
            [
                'brand'         => 'NOW Foods',
                'name'          => 'ميلاتونين 5mg لتحسين النوم',
                'slug'          => 'melatonin-5mg-now-foods',
                'description'   => 'ميلاتونين طبيعي 5mg لتنظيم دورة النوم والاستيقاظ. مثالي لمشاكل النوم وفارق التوقيت.',
                'price'         => 42.00,
                'old_price'     => 58.00,
                'image_url'     => 'https://images.unsplash.com/photo-1576671082168-1f03b13c57c1?w=300&q=80',
                'badge'         => 'new',
                'discount'      => 27,
                'rating'        => 4.5,
                'reviews_count' => 165,
                'stock'         => 90,
                'category_slug' => 'herbs',
            ],
            [
                'brand'         => 'BSN',
                'name'          => 'مكمل قبل التدريب NO Xplode',
                'slug'          => 'no-xplode-pre-workout-bsn',
                'description'   => 'مكمل ما قبل التمرين الأقوى. يمنحك طاقة انفجارية وتركيزاً عالياً وضخاً عضلياً مكثفاً.',
                'price'         => 155.00,
                'old_price'     => 200.00,
                'image_url'     => 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=300&q=80',
                'badge'         => 'new',
                'discount'      => 22,
                'rating'        => 4.9,
                'reviews_count' => 412,
                'stock'         => 35,
                'category_slug' => 'energy',
            ],
        ];

        foreach ($products as $data) {
            $categorySlug = $data['category_slug'];
            unset($data['category_slug']);
            $data['category_id'] = $cats[$categorySlug];

            Product::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
